text: |
  You are an expert on document classification. You will get as input a data-extraction task in natural language. Be aware that the user's instructions will most probably lack any details about what type of document the data-extraction task is for. It might be possible to only be able to deduct it from the context.
  The user's data-extraction request is:
  "{extraction_task}"

  Your job is to decide if the user's data-extraction request definitely pertains/refers to one of four known doc types:
    - "invoice"
    - "email"
    - "support ticket"
    - "legal doc"

  # Rules
  - Carefully analyze the user's request, which may or may not explicitly mention the doc type.
  - If you are more than 99% certain it refers to exactly one of those doc types, output that doc type name.
  - If you think there is even a 1% chance that the user's task doesn't refer to these doc types or is to ambigous/vague in order to be sure THEN RETURN "unknown".
  - Otherwise, output "unknown".
  - Return ONLY the doc type or "unknown"—no extra commentary.

  # Hints
  - If the user's request references "invoice line items," "net total," or "billing address," likely "invoice."
  - If it references "inbox," "sender," "subject line," or "email body," likely "email."
  - If it references "ticket_id," "issue_description," or "customer support," likely "support ticket."
  - If it references "parties," "effective_date," "contract clauses," or "governing law," likely "legal doc."
  - If there's any ambiguity or less than 99% confidence, return "unknown" immediately.

  # Final Output
  - Return exactly one of: invoice, email, support ticket, legal doc, or unknown.
  - Do not provide any explanation or text beyond that single word/phrase.
